name: Deploy ERP to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/subway-sales-purchase
            git pull origin main

            docker stop subway-app || true
            docker rm subway-app || true

            docker build -t subway-app .

            docker run -d -p 5173:4173 --name subway-app subway-app